name: space_gen
description: An OpenAPI generator.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  args: ^2.4.2
  collection: ^1.19.1
  equatable: ^2.0.7
  file: ^7.0.0
  http: ^1.4.0
  mason_logger: ^0.2.8
  meta: ^1.10.0
  mustache_template: ^2.0.0
  path: ^1.8.3
  scoped_deps:
    git:
      url: https://github.com/shorebirdtech/shorebird.git
      path: packages/scoped_deps
  version: ^3.0.2
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
  mocktail: ^1.0.4
  test: ^1.21.0
  very_good_analysis: ^7.0.0
